{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.11.0.aar",
          "url": "media3-exoplayer-1.11.0.aar",
          "size": 1703621,
          "sha512": "b7c3e57181f82182c6884d283a9afc6a43e8892c9829eea4f4e0373a5532f9c65b000b3a61e517f44700b3b17fd6a97b05bd5efd96d3659f903b0a633e2dd807",
          "sha256": "d3d22bc77cb92237587407d8dfbbf290f10e4895f468903c294d77f976ab0a70",
          "sha1": "6faf495efdd56db34bfb701b6a7f0d010389b71c",
          "md5": "4330dbdd4a514dd400758543f2814789"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.11.0.aar",
          "url": "media3-exoplayer-1.11.0.aar",
          "size": 1703621,
          "sha512": "b7c3e57181f82182c6884d283a9afc6a43e8892c9829eea4f4e0373a5532f9c65b000b3a61e517f44700b3b17fd6a97b05bd5efd96d3659f903b0a633e2dd807",
          "sha256": "d3d22bc77cb92237587407d8dfbbf290f10e4895f468903c294d77f976ab0a70",
          "sha1": "6faf495efdd56db34bfb701b6a7f0d010389b71c",
          "md5": "4330dbdd4a514dd400758543f2814789"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.11.0-sources.jar",
          "url": "media3-exoplayer-1.11.0-sources.jar",
          "size": 1231892,
          "sha512": "9e6d107fd6d265fefd9c90babf9dd3a0a93fe379b09da59d791daa101d793da49de0b5660cb56b625516580fe5842ec2652e98541ff4f810bdfea50f3b701e1a",
          "sha256": "ced7bf8c4ef0d48d65a0070b4c2a35aaaeadb16d6c3d296a34ab289702916996",
          "sha1": "22a1497d67e0f5bbdc163bf8c4d0408439876e18",
          "md5": "999e484580963a6e7758f9aa1cbfdb20"
        }
      ]
    }
  ]
}
