group 'com.ryanheise.just_audio'
version '1.0'
def args = ["-Xlint:deprecation","-Xlint:unchecked"]

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.8.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
          url = project(':just_audio').file('repo')
        }
    }
}

project.getTasks().withType(JavaCompile) {
    options.compilerArgs.addAll(args)
}

apply plugin: 'com.android.library'

android {
    sourceSets {
        main {
            java {
                srcDirs = ['src']
            }
        }
    }
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'com.ryanheise.just_audio'
    }
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    def exoplayer_version = "1.9.0-o"

    // main player dependencies
    implementation "androidx.media3:media3-exoplayer:$exoplayer_version"
    implementation "androidx.media3:media3-exoplayer-dash:$exoplayer_version"
    implementation "androidx.media3:media3-exoplayer-hls:$exoplayer_version"
    implementation "androidx.media3:media3-exoplayer-smoothstreaming:$exoplayer_version"
    
    // player core dependencies
    implementation "androidx.media3:media3-decoder:$exoplayer_version"
    implementation "androidx.media3:media3-extractor:$exoplayer_version"
    implementation "androidx.media3:media3-common:$exoplayer_version"
    implementation "androidx.media3:media3-container:$exoplayer_version"
    implementation "androidx.media3:media3-database:$exoplayer_version"
    implementation "androidx.media3:media3-datasource:$exoplayer_version"

    // extension dependencies
    implementation "androidx.media3:media3-decode-av1:$exoplayer_version" // av1 extension
    implementation "androidx.media3:media3-decode-ffmpeg:$exoplayer_version" // ffmpeg extension
    implementation "androidx.media3:media3-decode-flac:$exoplayer_version" // flac extension
    // implementation "androidx.media3:media3-decode-iamf:$exoplayer_version" // iamf extension
    implementation "androidx.media3:media3-decode-opus:$exoplayer_version" // opus extension
    implementation "androidx.media3:media3-decode-vp9:$exoplayer_version" // vp9 extension

    implementation "androidx.annotation:annotation:1.8.1"
}
