{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-av1",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0.aar",
          "url": "media3-decoder-av1-1.11.0.aar",
          "size": 2292134,
          "sha512": "11a4d173c9cb51fc20b7ed15ef9166ffa4784ff4c4bcec2d9817e17b7a14a3544b04fa91384acca0fa523b01c2ec8f62357ad8a7180f8695f49f4cf6939ac17a",
          "sha256": "c033f772e146aea2b00fe8021065516e41a051bf53d544a3e1c4a91a834243fa",
          "sha1": "7a7e9df21f162ecb85d7b054eb415ca71166ae44",
          "md5": "498c2cfd696811108abffce19e14e90d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0.aar",
          "url": "media3-decoder-av1-1.11.0.aar",
          "size": 2292134,
          "sha512": "11a4d173c9cb51fc20b7ed15ef9166ffa4784ff4c4bcec2d9817e17b7a14a3544b04fa91384acca0fa523b01c2ec8f62357ad8a7180f8695f49f4cf6939ac17a",
          "sha256": "c033f772e146aea2b00fe8021065516e41a051bf53d544a3e1c4a91a834243fa",
          "sha1": "7a7e9df21f162ecb85d7b054eb415ca71166ae44",
          "md5": "498c2cfd696811108abffce19e14e90d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0-sources.jar",
          "url": "media3-decoder-av1-1.11.0-sources.jar",
          "size": 11543,
          "sha512": "f6885d2a7c0c88a9dcedd2dc276f9d5a19a5783237b69f6980f8d5b00b046cfa10c8d3db9961536d62581c2ce38935b9d4dec38f4b71f32c4436f6d98be12cd7",
          "sha256": "332832813bd15ebde22ca951a5dbbffd7dc6e9c3ed1cdc60f58f7cb7dc4596e3",
          "sha1": "27fbcdc7214fa6d87fc64e24f1d581040d209b17",
          "md5": "0e46ed2c1f5449ab0becff6c2cdf38a1"
        }
      ]
    }
  ]
}
