{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-flac",
    "version": "1.8.0-o",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0-o"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-flac-1.8.0-o.aar",
          "url": "media3-decode-flac-1.8.0-o.aar",
          "size": 588133,
          "sha512": "6f383b1d4ef1d2b971689d2e6014d9b390d14672ac56ec952f0c7d511fbfcf845b409d6984eaf592c6ebbca907f7740c3b8cdfa9a2ba7db35dcee0f2f02e3c53",
          "sha256": "e1a6027416d8effa1616b341f8009783d31a5061e5046c1d9edcf96e1d9f30e6",
          "sha1": "54068904ed4fecd2fcc48b9d0984d6471f51bdf4",
          "md5": "85720e809b40fd7ab325114e56c5eb8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0-o"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0-o"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-flac-1.8.0-o.aar",
          "url": "media3-decode-flac-1.8.0-o.aar",
          "size": 588133,
          "sha512": "6f383b1d4ef1d2b971689d2e6014d9b390d14672ac56ec952f0c7d511fbfcf845b409d6984eaf592c6ebbca907f7740c3b8cdfa9a2ba7db35dcee0f2f02e3c53",
          "sha256": "e1a6027416d8effa1616b341f8009783d31a5061e5046c1d9edcf96e1d9f30e6",
          "sha1": "54068904ed4fecd2fcc48b9d0984d6471f51bdf4",
          "md5": "85720e809b40fd7ab325114e56c5eb8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-flac-1.8.0-o-sources.jar",
          "url": "media3-decode-flac-1.8.0-o-sources.jar",
          "size": 15751,
          "sha512": "dce908022addbc0fe0ecd6429a1a0db0f2924a75062f2e2778ffde6585477c2743ce2010ed5e73e3deca996c885fa0a592d3c11aaff2e272e558c759123b8f7e",
          "sha256": "3cc0b706c1715a904b99e707a895ed14855c8742492b404f1d60e821ae360715",
          "sha1": "ba92fd379739247603971d24fad2e5c0ca85569d",
          "md5": "54e71ac85f0763601820f41d4459a339"
        }
      ]
    }
  ]
}
