{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.0.aar",
          "url": "media3-extractor-1.11.0.aar",
          "size": 824206,
          "sha512": "73cde0a18cf03dd935e0278e4db855a6d0db6fc61e1835b22c36f021d2a988ac8a9d625fd850d2ee28c0ae4b420705833f91bedb723c77ff5ca305e366e847c2",
          "sha256": "5837cf1e9d46a03f16f14fa60cefc457bfa181e9b9ace9ae94dfcde77ca67f72",
          "sha1": "f9191cbc5cb06383e2dd143acf41d7b718bf11ad",
          "md5": "ad7155970d22334c9c447fb4d71b4a01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.0.aar",
          "url": "media3-extractor-1.11.0.aar",
          "size": 824206,
          "sha512": "73cde0a18cf03dd935e0278e4db855a6d0db6fc61e1835b22c36f021d2a988ac8a9d625fd850d2ee28c0ae4b420705833f91bedb723c77ff5ca305e366e847c2",
          "sha256": "5837cf1e9d46a03f16f14fa60cefc457bfa181e9b9ace9ae94dfcde77ca67f72",
          "sha1": "f9191cbc5cb06383e2dd143acf41d7b718bf11ad",
          "md5": "ad7155970d22334c9c447fb4d71b4a01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.11.0-sources.jar",
          "url": "media3-extractor-1.11.0-sources.jar",
          "size": 712440,
          "sha512": "66ecadb1c49ab9321f66b1a71f5f22c1332e05044c0e44adaae106fd5532022e6e60f546b38ed072c892c53670cdd78a85a137d7904dad0e149fd77f3207488d",
          "sha256": "6bda7cfa3991cc377940e1e62d9e50a4261ce8b026c0f2409a4399d605a34fb3",
          "sha1": "da5a53227d950f76b60ac072429feaeb31828397",
          "md5": "472428a9a021d38bbd7037e27ad3fc03"
        }
      ]
    }
  ]
}